apiVersion: v1
kind: Service
metadata:
  name: result-services
  labels:
    name: : voting-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targePort: 80
  selector: 
    labelMatch:
      name: result-app-pod
      app: demo-voting-app



